### PR TITLE
Fix linter errors

### LINKED ISSUE #41: fix linting errors
the new linting causes the build to fail

### PR DESCRIPTION
**Pull request by evaporei**
## What does this PR do?

- Fixes linter errors;
- Adds linter step on `travis-ci` to verify that every Pull Request has the code on the project standard;

This closes https://github.com/markd/markd/issues/41.

### CODE REVIEW

**Review by redxtech — APPROVED** [review]
looks fine to me.

**Comment by lostdesign** [comment]
Well #43 is now the solution for #41

**Comment by evaporei** [comment]
@lostdesign So this PR will be ignored? :(

**Comment by evaporei** [comment]
Well, since someone already solved the issue, and this is being ignored, I will close it :slightly_frowning_face:

**Comment by bdbch** [comment]
@otaviopace sorry for this, we're still quite young on the open source space when it comes to managing open repos! The solution provided on the other PR looked good since it used Prettier which I really like.

Otherwise your PR looked good. I guess it was done for Hacktoberfest? Will it still be counted for your progress?

**Comment by evaporei** [comment]
@bdbch no problems :slightly_smiling_face:. Also `hacktoberfest` only counts for PRs opened, not merged, so no worry.

**Pull request closed without merging**
